### ISSUE TITLE
Have to run multiple times to download all tweaks

### ISSUE THREAD

**Issue by oooooooooooooooo** [UsrLightmann/IAmSpeed#3]
And even then, after 5 runs several tweaks were not installed. Not sure what can be done about this since I'm sure a big part of the issue is that the downloads are timing out from the repo.

Maybe prioritize smaller file sizes the first run around?

**Comment by UsrLightmann** [comment]
Hey,

Thanks for reporting this!

That's odd. Downloads shouldn't time out nor should you have to run the restore more than once. 

Two things: 1) Do the packages installed after each restore differ (i.e., are some packages not installed during some restores, but are during others)? 2) Are the several tweaks in question paid tweaks by chance? 

Thanks in advance!

**Comment by oooooooooooooooo** [comment]
Yes in general they are different. I’m only suspecting time outs because when I manually tried to install more than 25 tweaks at a time they would do the same thing where 2-3 would fail and then with zebra is have to redo them all since it wouldn’t accept installing tweaks from the queue partially.

Out of the tweaks left over it was a mix of paid and unpaid.

**Comment by UsrLightmann** [comment]
Hmm, that's not good. The paid tweaks not being installed makes sense, since apt can't verify a purchase with the repo, but I'm not sure if it's actually timing out for the others or not. 

Are you sure that you have all of the relevant repos installed? Also, what were the free packages that didn't install after all of your attempts? 

If you do have all of the relevant repos installed, I can run you through the restore process manually, so we can see if apt encounters any issues.

Thanks again!

**Comment by UsrLightmann** [comment]
I've attempted to fix this issue in v1.0.4 which should be live in the next 12 hrs. If you could give it a go once it's been released and let me know if your issue has indeed been resolved, that would be super helpful. Thanks in advance!

**Comment by UsrLightmann** [comment]
Closing due to lack of response. *Should* be fixed in v1.0.4.

**Comment by davidiesel** [comment]
Bro none are working dont know what the problem is it stuck ag the first in iamlazy and just the spinners circles in iamspeed

David Oliveira 
JMJ


On 13-Jan-2022, at 11:18, Lightmann ***@***.***> wrote:

﻿

Closing due to lack of response. Should be fixed in v1.0.4.
